server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: loginMicroservices
          uri: http://localhost:8081
          predicates:
            - Path=/service/login/**

        - id: resourceMicroservices
          uri: http://localhost:8082
          predicates:
            - Path=/resource/body/**